### ISSUE TITLE
Interrupts dont Get Logged - Build 50 

### ISSUE THREAD

**Issue by RealZwox** [Geigerkind/DPSMateTBC#12]
Titel + Alle Modules are Active. (It was in a Raid. Im not sure if its the same in a Group)

I could not test it in the Build 51 but when you done no changes to Interrupts then its still a Issue.

**Comment by tdymel** [comment]
Be a little more specifc which interrupts are not working.
See the interrupt system has many parts for stuns, silence etc.

**Comment by tdymel** [comment]
Okay, there had been a lua error, not sure if you show lua errors in your interface, but this is fixed now
