### ISSUE TITLE
[Request] Clear Combatlog Entries

### ISSUE THREAD

**Issue by RealZwox** [Geigerkind/DPSMateTBC#13]
There is a problem with the 2.4.3 Client that after some time the Combatlog bugs out and nothing shows up anymore.

This results in Corrupted Log Files. The only way too fix this is to use 
`/script CombatLogClearEntries();
`

Is it possible that you maybe can include a function in DPSMateTBC, that uses this script like every 5 Min?

Cause i cant upload logs if i forget that even ones. And thats realy sad.

**Comment by tdymel** [comment]
sure

**Comment by RealZwox** [comment]
Is it realy happen? :O 

Make it like every 30 Sec just to be safe :) <3

**Comment by Evolvee** [comment]
local f = CreateFrame("frame",nil, UIParent); 
f:SetScript("OnUpdate", CombatLogClearEntries);

zwox noob
