### ISSUE TITLE
Player Classcolor not Correct / Player Class Icon not Correct - Build 51

### ISSUE THREAD

**Issue by RealZwox** [Geigerkind/DPSMateTBC#14]
I deleted all Settings of DPSMate and also cleared the Cache.

The Classicon depends on wich class is above you after you done the first dmg spell. But sometimes that changes during the Fight. (Wierd i know :D ) 

![wowscrnshot_061517_162123](https://user-images.githubusercontent.com/12686136/27187412-7349cc8c-51eb-11e7-93b8-128f08bd7d49.png)
![wowscrnshot_061517_163321](https://user-images.githubusercontent.com/12686136/27187416-740a7946-51eb-11e7-93bc-fc399c075c2a.png)

**Comment by RealZwox** [comment]
Note: It was fine on Build 50

**Comment by Redtuzk** [comment]
Getting the same thing, although it isn't fixed when i revert to build 50.

**Comment by tdymel** [comment]
Okay^^ Will see if I can find some quick fix

**Comment by RealZwox** [comment]
take your time its not a major issue^^

**Comment by tdymel** [comment]
Fixed
