### ISSUE TITLE
More a question!

### ISSUE THREAD

**Issue by jonomurphy** [Geigerkind/DPSMateTBC#18]
Sorry, I know this isn't the place to ask! I will delete issue if needed.

I really want to use this as I like the options available, and will try to get my raiding guild using it. Is it as accurate as recount? Is there also an option to show threat? If so, I could use this over both Omen and Recount.

Love the look! your work is amazing.

**Comment by tdymel** [comment]
It should be as inaccurate as recount is^^
The goal of the addon is more to extend the information you have.
The threat option is not available in TBC. This is a vanilla only feature yet.
Even there the goal of this feature is not to replace existing threatmeters but rather to give you an idea how you generated threat

cheers!
