### ISSUE TITLE
Seit dem letzten Update funktioniert DpsMate nicht mehr

### ISSUE THREAD

**Issue by armaggedon1** [Geigerkind/DPSMateTBC#6]
Seit dem letzten Update prudziert DpsMate nur noch Fehlermeldungen:

![wowscrnshot_031617_223416](https://cloud.githubusercontent.com/assets/16654620/24019670/357b1026-0a99-11e7-8aab-e753b9c2e9d7.jpg)

Neuinstallation inkl. löschen aller lua Dateien hat leider auch nix gebracht.

**Comment by tdymel** [comment]
Fixed, danke :>
