### ISSUE TITLE
Weiterhin viele Fehlermeldungen und Fehler

### ISSUE THREAD

**Issue by armaggedon1** [Geigerkind/DPSMateTBC#7]
DpsMate funktioniert jetzt nur teilweise, das heisst viele Spieler im Raid tauchen gar nicht auf, oder erst sehr spät im Raidverlauf, daher stimmen die Werte leider gar nicht und somit auch die Logs.

Hier wieder Screens der Fehlermeldungen:

![wowscrnshot_032317_234846](https://cloud.githubusercontent.com/assets/16654620/24273628/a59144b8-1023-11e7-875b-fd9b80f1f4f2.jpg)
![wowscrnshot_032317_234851](https://cloud.githubusercontent.com/assets/16654620/24273665/ca94552a-1023-11e7-9dc1-897c53905735.jpg)
![wowscrnshot_032317_234906](https://cloud.githubusercontent.com/assets/16654620/24273668/cd0ba178-1023-11e7-9c96-0df9fa8e63e1.jpg)

**Comment by tdymel** [comment]
Sorry, hab lang nicht reingeschaut, uni :<
Werd mich darum kümmern!
