### ISSUE TITLE
Reset Button is not working

### ISSUE THREAD

**Issue by RealZwox** [Geigerkind/DPSMateTBC#8]
[Youtube Bug Report](https://www.youtube.com/watch?v=uLTNHt_M384)

**Comment by tdymel** [comment]
aight! 
Will try to fix it this weekend.
cheers!

**Comment by RealZwox** [comment]
Nimm dir zeit ;) Netherwing is noch nich draußen also eilt es nich. Ich reporte einfach mal was ich so finde

**Comment by tdymel** [comment]
I can't reproduce the bug :/
Maybe some other addon causes the issue?

**Comment by tdymel** [comment]
Are you in a raid or group?

**Comment by RealZwox** [comment]
I was in a group

**Comment by tdymel** [comment]
Okay. Fixed it, please enable lua error messages next time :>
Thanks!
