### ISSUE TITLE
Empty "Unknown" Segments

### ISSUE THREAD

**Issue by RealZwox** [Geigerkind/DPSMateTBC#9]
It happens all the time so its not a rare Bug. 

Segments are Empty and flaged as "Unkown"
Maybe happens when you kill a critter.

You can see my Settings i use down below.

![wowscrnshot_060717_034334](https://user-images.githubusercontent.com/12686136/26858770-90af092c-4b33-11e7-8ab3-41effcc9213a.jpg)

**Comment by tdymel** [comment]
Should also happen less
